name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project dependencies
        run: uv sync --group dev

      - name: Run Ruff lint checks
        run: uv run ruff check . --output-format=github

      - name: Run Ruff format checks
        run: uv run ruff format . --check