[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "auditorydecoding"
version = "0.1.0"
description = "Auditory decoding of brain activity in different animals"
readme = "README.md"
requires-python = ">=3.11, <3.14"

dependencies = [
    "matplotlib>=3.10.8",
    "mne==1.11.0",
    "mne-bids==0.18",
    "scikit-learn==1.7.2",
    "torch-brain",
    "torch>=2.6.0",
    "scipy>=1.17.1",
    "temporaldata",
    "pyyaml>=6.0.3",
    "ray>=2.10",
    "seaborn>=0.13.2",
    "ipykernel>=7.2.0",
    "pywavelet>=0.2.10",
    "pywavelets>=1.9.0",
    "pydmd>=2025.8.1",
    "umap-learn>=0.5.12",
    "plotly>=6.8.0",
]

[tool.uv.sources]
torch-brain = { git = "https://github.com/neuro-galaxy/torch_brain", branch = "main" }
brainsets = { git = "https://github.com/neuro-galaxy/brainsets", branch = "suarez/mne-bids-utils" }

[dependency-groups]
dev = ["pre-commit>=4.5.1", "ruff>=0.15.4"]
notebooks = ["ipykernel>=7.2.0"]

[tool.hatch.build.targets.wheel]
packages = ["auditorydecoding"]

[tool.ruff]
line-length = 80
format.preview = true
extend-exclude = ["*.ipynb"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.hatch.build.targets.sdist]
include = ["auditorydecoding*"]
